# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2024-03-19 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('sex', models.IntegerField(choices=[(1, 'male'), (2, 'female'), (0, 'no idea')], default=0, verbose_name='sex')),
                ('profession', models.CharField(max_length=100, verbose_name='profession')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('qq', models.CharField(max_length=100, verbose_name='qq')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('status', models.IntegerField(choices=[(0, 'apply'), (1, 'pass'), (2, 'refuse')], default=0, verbose_name='审核状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
            },
        ),
    ]
